### ISSUE TITLE
Connecting accounts for leaderboards

### ISSUE THREAD

**Issue by mishushakov** [opensourcepledge/osspledge.com#22]
What would be cool if I could connect my GitHub Sponsors account and OpenCollective to Open Source Pledge to get real-time scores

**Comment by vladh** [comment]
I think this could be a cool thing to look at in the future. For the initial launch, I think focusing on the schema-based self-reporting makes sense, because it conveniently simplifies things, in that there's only one way to report, and it works for everyone.

**Comment by chadwhitacre** [comment]
I'm gonna go ahead and close this out as it really fits more with the individual use case (#21) and we're focusing on the company use case for the foreseeable future. Feel free to mention this and any further brainstorms related to the individual case on #21, @mishushakov. 🙏
