### ISSUE TITLE
Switch canonical URL back to osspledge.com

### ISSUE THREAD

**Issue by chadwhitacre** [opensourcepledge/osspledge.com#25]
We're using osspledge.com on the billboard and have already started socializing it somewhat. Seems to be the preferred canonical url. I WILL ABIDE BY THE RESULTS OF THIS POLL.

<img width="589" alt="image" src="https://github.com/user-attachments/assets/ceb8915d-d805-46d1-bee7-e94d2af7ec85">

https://x.com/chadwhitacre_/status/1818955099042967631

**Comment by vladh** [comment]
Democracy in action! #26

**Comment by Delta456** [comment]
W for `osspledge.com`

**Comment by chadwhitacre** [comment]
I merged #26 and made configuration changes to this repo and the other one (the redirect). Waiting for everything to settle.

https://osspledge.com/
https://opensourcepledge.com/

**Comment by chadwhitacre** [comment]
Done!
