### ISSUE TITLE
Host an ecosystem partners kick-off

### ISSUE THREAD

**Issue by chadwhitacre** [opensourcepledge/osspledge.com#37]
The primary audience for OSS Pledge is companies. However, if successful, we will 10x the funds flowing into FOSS, and we need to have an open dialogue with other ecosystem stakeholders, including individual maintainers, FOSS foundations, and funding platforms. 

This ticket is about hosting a kick-off information session, sometime probably in early to mid-September, at least a couple weeks before we launch the OOH campaign (#11). It seems likely that we will need some long-term communication channels possibly including a regular call, but for now let's focus on a kick-off event.

--------

Two sessions on **September 5**:

- 6am PST / 9am EST / 3pm CET
- 4pm PST / 7pm EST / 9am AEST

--------

60 minute agenda:

- 5 - welcome
- 10 - intro to oss pledge
- 40 - open floor for questions and discussion
- 5 - wrap-up

**Comment by chadwhitacre** [comment]
@Ethan-Arrowood and I met to work on this. Here's [a messy doc we started](https://docs.google.com/document/d/1YwD5sJJn9RNX53beE3qEgl5a18Pe2Lw-7Q5HIgEGi-w/edit?usp=sharing).

**Summary:**

- tentatively scheduling for **[September 5 from 9:00 to 10:00 AM US/Pacific](https://time.is/9am_5_Sept_2024_in_San_Francisco/New_York/London/Berlin/Sydney?Open_Source_Pledge_%E2%80%93_Partner_Kick-off)**
- invite list is all FOSS foundations and funding platforms
- open call, will be recorded for sharing
- 60 minute agenda:
  - 5 - welcome
  - 10 - intro to oss pledge
  - 45 - open floor for questions and discussion
  - 10 - wrap-up - who is our point person?
- Primary goal is to gather impacted maintainer reps and get them to tell us who they want their representative(s) to be as we build out the Pledge.

**Actions items:**

- @Ethan-Arrowood to draft an intro email.
- @Ethan-Arrowood to start a spreadsheet with contact info for foundations and platforms.
- @chadwhitacre and @Ethan-Arrowood to review email and sheet together.
- @Ethan-Arrowood to reach out to contacts (cc: @chadwhitacre) to announce the call.

@Ethan-Arrowood Are there any "must have" attendees? I'm thinking OSI, for example. Anyone we want to make sure can commit to being at the event?

**Comment by chadwhitacre** [comment]
I sent an email to OSI (cc: @Ethan-Arrowood @selviano).

**Comment by Ethan-Arrowood** [comment]
Started email draft: https://docs.google.com/document/d/1_BnYw205wm4GWR8hZF1w75qIKecWKsGmsv_7Eyc57xw/edit?usp=sharing

If you want comment/edit access just ask and I can add you. 

Working on spreadsheet next.

**Comment by chadwhitacre** [comment]
@selviano and I just had a call with OSI, they are down to participate and September 5 works for them. 👍

**Comment by Ethan-Arrowood** [comment]
Getting started on the contact spreadsheet here: https://docs.google.com/spreadsheets/d/1PB6DQ9vVlX9DyarP1OkSF_BYxiqqULhJQ43FtuqD6xc/edit?usp=sharing

Please let me know if you want edit access.

Would appreciate if folks take a look and include any contact emails they personally know - and you can leave a comment if you'd like to be CC'ed on that contact chain. 

I'm hoping to send emails out by Monday the 19th at the latest. As the list gets filled in I will start sending invites earlier too.

**Comment by Ethan-Arrowood** [comment]
This spreadsheet was generated from the FOSS Foundation list: https://github.com/Punderthings/fossfoundation/blob/main/_foundations/list.json

**Comment by Ethan-Arrowood** [comment]
I finished the contact list - got as many emails as I could find. Lots of contact forms which will require manual submission. Lets chat today how to execute sending out invites

**Comment by chadwhitacre** [comment]
Email is out!

I forwarded to contacts at OSI, GitHub, OC, PSF, Django, Ruby Central, PHP, JS, SFC, Sustain ...

**Comment by chadwhitacre** [comment]
Dialing back to a simpler meeting outcome: informational only, no ask of maintainers / foundations / partners at this point.

**Comment by Ethan-Arrowood** [comment]
I'm not sure if everyone is seeing the same replies that i am, but a number of organizations bounced. 

A lot of folks are replying with excitement too! 

I'll do my best to keep it all organized in the spreadsheet. 

@chadwhitacre please send me the event invites as soon as you figure that out. I'd like to get that to people a couple days ahead of time. 

Should we consider some sort of Twitter outreach here? maybe a like "Are you an open source organization interested in learning more about OSSPledge? We are hosting info sessions calls on September 5th. DM/Reply for details". I don't think my network is large enough so maybe this is something you could send @chadwhitacre ? Or is your personal contacts + the list good enough for this call?

**Comment by chadwhitacre** [comment]
How about this for scheduling? Can you test this out @Ethan-Arrowood (et al.) and I'll confirm it's working before we blast it out?

https://cal.com/osspledge/ecosystem-kick-off?month=2024-09&date=2024-09-05

**Comment by Ethan-Arrowood** [comment]
Nice works great!

**Comment by chadwhitacre** [comment]
Awesome, everything looks good on this side as well so I would say let's start sharing this out!

https://cal.com/osspledge/ecosystem-call

(Note URL tweak ... keeping it flexible for possible future usage.)

**Comment by chadwhitacre** [comment]
https://x.com/chadwhitacre_/status/1825958122621645219

**Comment by chadwhitacre** [comment]
@Ethan-Arrowood @vladh @selviano I believe I responded on all of the email threads related to the ecosystem kickoff call that were in my court, and cc'd yinz. We're at three guests each for the two sessions right now.

**Comment by mkurz** [comment]
> The primary audience for OSS Pledge is companies.

Hi, I'm an open-source maintainer funded by the community, not a company. Would it be possible for me to join the calls? (I'm very interested in this initiative and would like to listen in as a passive observer, just to hear what will be discussed. Nothing more.)

**Comment by mkurz** [comment]
@chadwhitacre Great, I just registered for the first event. Not sure if I make it to the second one because it's in the middle of the night here. See you next week :+1:

**Comment by chadwhitacre** [comment]
Thank you to everyone who joined one of our calls yesterday! We had 20 attendees across the two calls, representing the following organizations and projects (alphabetical):

1. Distribute Aid
1. Django Software Foundation
1. FreeBSD Foundation
1. Kotlin Foundation
1. Open Source Collective
1. Open Source Initiative
1. Open Source Pledge
1. PHP Foundation
1. Play Framework
1. Ruby Central
1. Rust Foundation
1. Thanks.dev
1. WiX Toolset

Here are the recordings: [one](https://drive.google.com/file/d/1UEumvfu8GEbe4jxtciO7SL6CzMGyW7Gd/view), [two](https://drive.google.com/file/d/1JdZAqySRXM3P1gRRBhUhdCZBoPTJGtCJ/view). I'm going to close this ticket out with that and pick up over in #5 and #11.
