### ISSUE TITLE
Add leaderboards

### ISSUE THREAD

**Issue by chadwhitacre** [opensourcepledge/osspledge.com#42]
We should add leaderboards sooner rather than later, so there's no surprise after companies onboard.

I think segmenting leaderboards by number of devs may make it easier to onboard larger members, because larger enterprises will have a much longer approval cycle for spend on maintainers. With this we would likely need to drop the hard minimum (which we're not enforcing in code yet afaik anyway).

We could then get some competition going between cohorts: "Companies with between 1000 and 10000 devs are giving more per dev than any other cohort."

**Comment by mitsuhiko** [comment]
I think an interesting leaderboard would be streaks (eg: have been doing that for X cycles).

**Comment by chadwhitacre** [comment]
Additional discussion is in the PR #43 but tl;dr we are shifting from "leaderboards" to "company explorer."
