### ISSUE TITLE
Funding platforms biases to 501(c)(6) and commercial entities

### ISSUE THREAD

**Issue by robbat2** [opensourcepledge/osspledge.com#50]
Before you read the rest of this, I want to be VERY clear that I'm thankful for this work, it's much needed; and I've got a very worn tidelift shirt to prove it. It's also NOT the first attempt in the community to do this, I've watched - and intermittently benefited as a maintainer, going back to OpenLogic in the 2005-2006 era, in addition to occasional consulting work for companies that wanted to use the projects where I was a maintainer and/or author.

https://github.com/opensourcepledge/osspledge.com/commit/b8c3e5dbcbc473dd819a80b2f444ba8dfaf7c399 describes the commit as `Be neutral about platforms`, but the entire list has a bias already: those platforms that profit off the donation margin.

Some of these include underlying transaction fees, but the data is not transparent; and they are heavily weighted towards commercial entities, and US 501(c)(6) entities that do not meet the definition of non-profit in some parts of the world.

- Buy Me a Coffee: 5% margin https://help.buymeacoffee.com/en/articles/4539170-frequently-asked-questions#is-there-a-fee-to-use-buy-me-a-coffee-
- GitHub sponsors: 0% margin for individual donors, 6% margin for organization donors; inclusive of transaction fees https://docs.github.com/en/sponsors/getting-started-with-github-sponsors/about-github-sponsors
- IssueHunt: 10% plus transaction fees, https://www.oss.fund/issue-hunt/
- Ko-fi: transaction fees plus 0-5% https://help.ko-fi.com/hc/en-us/articles/360002506494-Does-Ko-fi-take-a-fee#01H841GJ8PJH21PXY64231CFHB
- LFX Mentorship - fees not published; Linux Foundation project fees in general are transaction fees PLUS 9% first $1M, and 6% thereafter; The Linux Foundation does *NOT* transparently publish this, and it must be found in the Linux Foundation participation agreements [e.g. https://cdn.platform.linuxfoundation.org/agreements/openssf.pdf]
- Liberapay: transaction fees + 0% https://en.liberapay.com/about/faq#fees
- Open Collective: transaction fees + variable fees by fiscal host, inc 15% share to Open Collective https://opencollective.com/pricing
- Patreon: 5-12% plus transaction fees https://support.patreon.com/hc/en-us/articles/11111747095181-Creator-fees-overview
- Polar: 5% plus transaction fees https://polar.sh/#pricing
- StackAid: 7.5% plus transaction fees https://www.stackaid.us/#how-do-you-make-money
- Thanks.dev: 5% plus transaction fees https://thanks.dev/faq
- Tidelift: not clear on their website.

This issue will be followed by a PR to add some US 501(c)(3) fiscal hosts, as well as text to further reduce the above bias.

**Comment by chadwhitacre** [comment]
Closing with #51.
