### ISSUE TITLE
Convince DNS providers we're not malware

### ISSUE THREAD

**Issue by chadwhitacre** [opensourcepledge/osspledge.com#62]
I've seen this crop up a couple places. Latest from internal Sentry Slack:

> I was reading one of your posts on LinkedIn about https://osspledge.com/ however it seems to be blocked by my DNS provider as malware. I'm currently setup with something called [Canadian Shield](https://www.cira.ca/en/canadian-shield/). You may want to reach out to them to see what is going on with that so it can be unblocked

**Comment by vladh** [comment]
Resolving using Canadian Shield “DNS resolution only” [1] correctly returns our GitHub A record.

```
$ dig osspledge.com @149.112.121.10
...
osspledge.com.		86400	IN	A	185.199.109.153
```

Resolving using Canadian Shield “Malware and phishing protection” returns their “malware blocked” page:

```
$ dig osspledge.com @149.112.121.20
...
osspledge.com.		0	IN	A	99.83.179.4
```

> We’re sorry. This site contains malware content.
>
> The site you are trying to visit contains malicious content that may attempt to steal your personal or financial information. It has been blocked to avoid causing loss to you or harm to your device.

We have also received this potentially related report:

![screenshot](https://github.com/user-attachments/assets/1bbdf76c-cd74-4049-8174-92d3ec7e6386)

[1]: https://www.cira.ca/en/canadian-shield/configure/summary-cira-canadian-shield-dns-resolver-addresses/

**Comment by vladh** [comment]
I've contacted CIRA, who run Canadian Shield, to ask for help.

**Comment by vladh** [comment]
osspledge.com is listed on the Spamhaus Domain Blocklist: https://check.spamhaus.org/results?query=osspledge.com

I've opened a ticket with Spamhaus to ask for this to be corrected.

**Comment by chadwhitacre** [comment]
Weird. I wonder how that happened. 🤔

**Comment by chadwhitacre** [comment]
Maybe we need to set up SPF?

**Comment by vladh** [comment]
We do already have a deny-all SPF record:

```
$ dig osspledge.com txt
...
osspledge.com.		43200	IN	TXT	"v=spf1 -all"
```

But it shouldn't matter because we're not sending or receiving email at osspledge.com.

**Comment by Ethan-Arrowood** [comment]
When I sent out the partner email, I received a handful of replies that considered my message spam. However, I used my personal email, and the `osspledge.com` domain was only included in the content of the email.

**Comment by chadwhitacre** [comment]
> But it shouldn't matter because we're not sending or receiving email at osspledge.com.

My hypothesis was that we didn't have an SPF record and someone was spoofing us. Good that we have an SPF record, though. Agree this seems to not be the problem.

**Comment by chadwhitacre** [comment]
Another report: https://x.com/_st0012/status/1828891902076150183.

**Comment by vladh** [comment]
I've checked against many domain blacklists [^1][^2] and it seems like Spamhaus is the only one we're on. Handling this in a ticket with them.

[^1]: https://mxtoolbox.com/blacklists.aspx
[^2]: https://www.debouncer.com/blacklistlookup

**Comment by chadwhitacre** [comment]
Might be something to your experience, @Ethan-Arrowood. Just got this warning on an email @selviano sent out w/ me cc'd.

<img width="795" alt="Screenshot 2024-08-29 at 4 19 09 PM" src="https://github.com/user-attachments/assets/30c6d1b9-e544-4439-81be-0b82ad039d3f">

**Comment by vladh** [comment]
Yikes, wondering how many people from my original member recruiting batch got that. 😭

**Comment by selviano** [comment]
this gives me an excuse to follow up with everyone I sent the pitch deck to and hasn’t yet responded!

**Comment by chadwhitacre** [comment]
The plan all along. ;-)

**Comment by vladh** [comment]
We’ve been removed from the Spamhaus Domain Blocklist. 🎉

**Comment by chadwhitacre** [comment]
Woo-hoo! @st0012 @nicholas-codecov Can you retry and let us know if/when it's fixed for you?

**Comment by vladh** [comment]
Canadian Shield has also separately unblocked us. 🎉

**Comment by chadwhitacre** [comment]
Awesome! Thanks for reporting back, @nicholas-codecov. Gonna go ahead and close this out. 🎉
