### ISSUE TITLE
Comprehensively test website on mobile devices

### ISSUE THREAD

**Issue by vladh** [opensourcepledge/osspledge.com#68]

**Comment by chadwhitacre** [comment]
e.g.

![IMG_4804](https://github.com/user-attachments/assets/bd73794d-eeeb-4139-9427-6716072de2fd)

**Comment by vladh** [comment]
Thanks for this, will fix today.

**Comment by vladh** [comment]
Fixed above issue in 5074cc6ea82c7c1dcf56ea403a53e78c64e26ec8. Will do more tests.
