### ISSUE TITLE
Promote

### ISSUE THREAD

**Issue by chadwhitacre** [opensourcepledge/osspledge.com#7]
Our main planned promotion is an SF OOH campaign (billboards, buses, etc.) scheduled for October 7 - Nov 3. Art is due by Sept 17.

We also want to work with influencers, podcasters, media, etc. ([sheet 🔒](https://docs.google.com/spreadsheets/d/1kvt1bbhlqBNYZ9nrLrcWV0lGbtuLai3b-zqaO15lgtw/edit)).

### To Do

- [ ] #11
- [x] ~meet with Sentry devrel to identify influencers~ - _let's focus on #5 and let devfluencers happen organically_
- [ ] formal media training for Chad

**Comment by nehzatarmin** [comment]
@chadwhitacre I'm happy to reach out to our thanks.dev developer community to get them to share a tweet or a post. It might be more effective if we do one to one for the initial 50 maintainers, we just need to be very specific in terms of ask.

**Comment by chadwhitacre** [comment]
Awesome, thanks @nehzatarmin!

**Comment by chadwhitacre** [comment]
@selviano Are we doing any digital promotion during the OOH campaign?

**Comment by chadwhitacre** [comment]
I've been building out a video studio over the past couple months, and for my first video using the studio I made a short clip to accompany the "[Open Source Is a Restaurant](https://openpath.chadwhitacre.com/2024/open-source-is-a-restaurant/)" blog post. Here it is on [YouTube](https://www.youtube.com/watch?v=AZZyV0gk3TM) and [X](https://x.com/chadwhitacre_/status/1827024591299998077).

**Comment by chadwhitacre** [comment]
Not sure this ticket is adding value over others such as #11 and #37. Closing.
