### ISSUE TITLE
Redirect www.osspledge.com to osspledge.com

### ISSUE THREAD

**Issue by vladh** [opensourcepledge/osspledge.com#90]

**Comment by chadwhitacre** [comment]
Done in https://github.com/getsentry/ops/pull/12027 (private repo, also configured for fair.io, fsl.software, and opensourcepledge.com).

**Comment by chadwhitacre** [comment]
Should be good. @vladh Want to confirm and close?

**Comment by vladh** [comment]
LGTM :)
